package com.ciyato.launcher.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Real authenticated encryption for the Secure File Vault: AES-256-GCM with
 * a key generated and held inside the AndroidKeyStore. The raw key material
 * never leaves the keystore (not extractable, never written to disk) — only
 * ciphertext hits the filesystem.
 *
 * On-disk format for a vault file:
 *   byte 0        magic   (0xC7)
 *   byte 1        version (1)
 *   byte 2        IV length in bytes (12 for GCM)
 *   next ivLen    IV (random per file, generated by the keystore on encrypt)
 *   remainder     AES/GCM ciphertext, GCM auth tag included at the end
 *
 * Vault files written before this hardening pass don't carry that header —
 * they're raw bytes XORed against the app's package name. [verifyAndMigrate]
 * detects those and upgrades them in place without ever risking the original.
 */
object VaultCrypto {
    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS = "ciyato_vault_key_v1"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_BITS = 128
    // Byte constants can't be `const` — 0xC7 overflows Byte's literal range, and .toByte() is a
    // function call, which the compiler won't fold into a const initializer. Plain `val` instead.
    private val MAGIC: Byte = 0xC7.toByte()
    private const val VERSION: Byte = 1
    private const val HEADER_SIZE = 3 // magic + version + ivLen
    private const val TEMP_MARKER = ".vaulttmp"

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        keyStore.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun isVaultFormat(bytes: ByteArray): Boolean =
        bytes.size > HEADER_SIZE && bytes[0] == MAGIC && bytes[1] == VERSION

    /** Legacy scheme: raw bytes XORed against the app's package name. Not encryption — no key secrecy, no integrity. */
    private fun legacyXorDecode(bytes: ByteArray, packageName: String): ByteArray {
        val key = packageName.toByteArray()
        return ByteArray(bytes.size) { i -> (bytes[i].toInt() xor key[i % key.size].toInt()).toByte() }
    }

    /** Encrypts [plain] with AES-256-GCM under a fresh random IV and returns the headered vault-file bytes. */
    fun encrypt(plain: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, getOrCreateKey()) }
        val iv = cipher.getIV() // keystore-generated random IV; never reused across encrypt calls
        val cipherText = cipher.doFinal(plain)
        return ByteArray(HEADER_SIZE + iv.size + cipherText.size).also { out ->
            out[0] = MAGIC
            out[1] = VERSION
            out[2] = iv.size.toByte()
            iv.copyInto(out, HEADER_SIZE)
            cipherText.copyInto(out, HEADER_SIZE + iv.size)
        }
    }

    /** Decrypts headered vault-file bytes produced by [encrypt]. Throws if the header is missing/corrupt or the auth tag doesn't verify. */
    fun decrypt(vaultBytes: ByteArray): ByteArray {
        check(isVaultFormat(vaultBytes)) { "Not a recognized vault file" }
        val ivLen = vaultBytes[2].toInt() and 0xFF
        val cipherStart = HEADER_SIZE + ivLen
        check(vaultBytes.size > cipherStart) { "Truncated vault file" }
        val iv = vaultBytes.copyOfRange(HEADER_SIZE, cipherStart)
        val cipherText = vaultBytes.copyOfRange(cipherStart, vaultBytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        }
        return cipher.doFinal(cipherText)
    }

    /**
     * Encrypts [plain] and writes it to [file] without ever truncating an existing file in place:
     * the ciphertext is written to a sibling temp file first and only swapped in via [File.renameTo]
     * once that write is complete. A crash or process death mid-write leaves [file] exactly as it
     * was — either the old contents or absent, never a partial write.
     */
    fun storeFile(file: File, plain: ByteArray) = writeAtomically(file, encrypt(plain))

    /**
     * Writes [bytes] to [file] without ever truncating it in place: a sibling
     * temp file is written and flushed to disk first, and only swapped in by
     * rename once complete. A crash mid-write leaves [file] exactly as it was —
     * the old contents or absent, never half of either.
     *
     * The fsync matters and is easy to omit. Without it, rename can be durable
     * while the data it points at is still in the page cache, so a power loss
     * leaves a file that exists and is empty — which for a vault means the
     * plaintext is gone and the ciphertext never arrived.
     */
    private fun writeAtomically(file: File, bytes: ByteArray) {
        val parent = checkNotNull(file.parentFile) { "Vault file has no parent directory" }
        val tmp = File(parent, "${file.name}$TEMP_MARKER${System.nanoTime()}")
        try {
            FileOutputStream(tmp).use { out ->
                out.write(bytes)
                out.flush()
                out.fd.sync()
            }
            if (!tmp.renameTo(file)) throw IOException("Rename failed while saving ${file.name}")
        } catch (e: Exception) {
            tmp.delete()
            throw e
        }
    }

    /**
     * Largest file the vault will take, in bytes.
     *
     * Encryption here is whole-file: the plaintext, the ciphertext and the
     * copy handed to Cipher are all resident at once, so a large video can cost
     * several times its own size in heap and fail in the middle of a security
     * operation (F-017). Streaming authenticated encryption is the real answer
     * and is a larger change; until then the limit is enforced and stated rather
     * than discovered as an OutOfMemoryError.
     */
    const val MAX_VAULT_FILE_BYTES = 64L * 1024 * 1024

    /** Human reason a file cannot be vaulted, or null when it can. */
    fun rejectionReason(sizeBytes: Long): String? = when {
        sizeBytes <= 0L -> "That file is empty."
        sizeBytes > MAX_VAULT_FILE_BYTES ->
            "That file is larger than ${MAX_VAULT_FILE_BYTES / (1024 * 1024)} MB. " +
                "The vault encrypts a file whole, in memory, so bigger files are refused " +
                "rather than risked."
        else -> null
    }

    /**
     * Called once per vault file on unlock. If [file] is a legacy XOR-encoded file, decodes it with
     * the old scheme and re-encrypts it as AES-GCM in place via [storeFile] (interruption-safe — see
     * its doc). If [file] is already AES-GCM, this instead just decrypts it to confirm it is still
     * readable, so corruption is caught here with a clear failure rather than surfacing later as
     * silent garbage. Throws on failure; callers should wrap this per-file so one bad file doesn't
     * block the rest of the vault, and should leave the file untouched on failure — it will be
     * retried on the next unlock.
     */
    fun verifyAndMigrate(file: File, legacyPackageName: String) {
        val raw = file.readBytes()
        if (isVaultFormat(raw)) {
            decrypt(raw) // discarded — this call exists to prove the file still decrypts
            return
        }

        // "Not the current format" is NOT evidence of the legacy format.
        //
        // This branch used to accept that inference, and it is the most
        // dangerous line in the vault: a modern file whose first two bytes were
        // damaged would fail isVaultFormat, be XOR-"decoded" as though it were
        // legacy, and be re-encrypted over itself — destroying the only copy of
        // the plaintext while reporting success (F-016).
        //
        // A file carrying the magic byte is ours. If its version is one we do
        // not know, it came from a newer build or it is damaged; either way the
        // answer is to fail loudly and leave it alone, not to run a lossy
        // transform over it.
        if (raw.isNotEmpty() && raw[0] == MAGIC) {
            throw IOException(
                "${file.name} looks like a Ciyato vault file with an unrecognized version " +
                    "(${if (raw.size > 1) raw[1].toInt() else -1}). Left untouched.",
            )
        }

        val decoded = legacyXorDecode(raw, legacyPackageName)

        // Prove the migration is reversible BEFORE anything replaces the
        // original. The audit asks for migrate-verify-then-replace, and this is
        // the verify: re-encrypt, decrypt the result, and require the bytes back
        // exactly. If any step throws or the round trip disagrees, the original
        // file has not been touched.
        val reEncrypted = encrypt(decoded)
        val roundTripped = decrypt(reEncrypted)
        if (!roundTripped.contentEquals(decoded)) {
            throw IOException("${file.name} did not survive a migration round trip. Left untouched.")
        }

        writeAtomically(file, reEncrypted)
    }

    /**
     * True for a leftover [storeFile] temp file — the process can die between the temp write
     * finishing and the rename that swaps it in. Never the real vault file: it's safe to delete
     * outright, since the file it would have replaced was never touched until that rename step.
     */
    fun isTempArtifact(name: String): Boolean = name.contains(TEMP_MARKER)
}
