package com.ciyato.launcher

import com.ciyato.launcher.data.PermissionCapability
import com.ciyato.launcher.data.PermissionRegistry
import java.io.File
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Holds the permission registry to the manifest, and the manifest to the code.
 *
 * This test exists because of what it caught on the day it was written.
 * `PACKAGE_USAGE_STATS` was absent from the manifest while six screens called
 * `UsageStatsManager`, and Android's failure mode there is the quietest one it
 * has: `queryUsageStats` returns an empty list instead of throwing, and an app
 * that does not declare the permission is not listed on the Usage access
 * settings screen at all. So Insights, screen time, anomaly detection,
 * suggestions and the daily summary each showed a "grant access" prompt, sent
 * the person to a Settings page where Ciyato did not appear, and could never
 * succeed. Nothing logged. Nothing crashed. Six features were simply inert.
 *
 * The checks read the source manifest and, when a build has produced one that
 * is not older than it, the merged manifest too — because the merged one is
 * what ships, and libraries contribute permissions the source manifest never
 * mentions (F-184). See [manifestText] for why staleness is handled explicitly
 * rather than by preferring whichever file exists.
 */
class PermissionRegistryTest {

    /**
     * Permissions that are real but carry no user-facing decision, so a row in
     * the registry would be noise rather than governance. Kept explicit: adding
     * to this list is a deliberate act, not a silent omission.
     */
    private val notUserFacing = setOf(
        // Contributed by androidx.biometric. Gates the vault, hidden apps and
        // app lock; the person's decision is the biometric enrolment itself,
        // made in Android's settings, not a Ciyato permission.
        "android.permission.USE_BIOMETRIC",
        "android.permission.USE_FINGERPRINT",
        // Contributed by WorkManager so scheduled photo backup survives a
        // reboot and can hold the CPU while it runs.
        "android.permission.WAKE_LOCK",
        "android.permission.RECEIVE_BOOT_COMPLETED",
        "android.permission.FOREGROUND_SERVICE",
        // Notification posting, which Android already governs with its own
        // per-app toggle.
        "android.permission.POST_NOTIFICATIONS",
        // Generated by androidx.core for dynamically registered non-exported
        // receivers. Ciyato declares it to itself; nothing else can hold it and
        // it grants access to no user data.
        "com.ciyato.launcher.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
    )

    /**
     * The manifest text to check, and a label for failure messages.
     *
     * Source and merged are read TOGETHER rather than merged-if-present. The
     * first version of this preferred the merged manifest, and the first thing
     * it did was report a permission missing that had been added to the source
     * manifest minutes earlier: `testDebugUnitTest` does not rebuild the merged
     * manifest, so the file on disk was from an older build. A stale artefact
     * that produces a confident wrong answer is worse than no artefact.
     *
     * A merged manifest older than the source manifest is therefore ignored
     * outright, and the two are unioned when both are current — merging can add
     * library permissions but can never drop one the source declares.
     */
    private fun manifestText(): Pair<String, String> {
        val source = File("src/main/AndroidManifest.xml")
        assertTrue("no manifest found to check against", source.exists())

        val merged = listOf(
            "build/intermediates/merged_manifest/release/processReleaseMainManifest/AndroidManifest.xml",
            "build/intermediates/merged_manifest/debug/processDebugMainManifest/AndroidManifest.xml",
        ).map(::File)
            .filter { it.exists() && it.lastModified() >= source.lastModified() }

        if (merged.isEmpty()) return source.readText() to "source manifest (no current merged manifest on disk)"
        return (source.readText() + merged.joinToString(separator = " ") { it.readText() }) to
            "source + merged manifest"
    }

    private fun declaredPermissions(manifest: String): Set<String> =
        Regex("""<uses-permission[^>]*android:name="([^"]+)"""", RegexOption.DOT_MATCHES_ALL)
            .findAll(manifest)
            .map { it.groupValues[1] }
            .toSet()

    @Test
    fun `every declared permission is either registered or explicitly not user-facing`() {
        val (manifest, which) = manifestText()
        val unexplained = declaredPermissions(manifest)
            .filterNot { it in notUserFacing }
            .filter { PermissionRegistry.forPermission(it) == null }
            .sorted()

        assertTrue(
            "$which declares permissions with no PermissionCapability row: $unexplained. " +
                "Every sensitive capability needs a row - the Data Safety form, the privacy " +
                "policy and the in-app disclosure all read from it.",
            unexplained.isEmpty(),
        )
    }

    @Test
    fun `no row names a permission the app does not declare`() {
        val (manifest, which) = manifestText()
        // Checked against the whole manifest text, not just uses-permission:
        // a notification listener declares its permission on the service.
        val stale = PermissionRegistry.capabilities
            .map { it.permission }
            .filterNot { manifest.contains(it) }
            .sorted()

        assertTrue(
            "the registry describes permissions absent from the $which: $stale. " +
                "A row for a permission that is not declared is a promise to a reviewer " +
                "that the code does not keep.",
            stale.isEmpty(),
        )
    }

    @Test
    fun `the permissions the usage features depend on are actually declared`() {
        // Named explicitly rather than left to the general check, because this
        // is the one that was missing and the symptom was silence.
        val (manifest, which) = manifestText()
        listOf(
            "android.permission.PACKAGE_USAGE_STATS" to "UsageStatsManager returns an empty list and Ciyato is not listed under Usage access",
            "android.permission.QUERY_ALL_PACKAGES" to "the launcher cannot see installed apps",
            "android.permission.READ_MEDIA_IMAGES" to "Photos cannot read the library",
        ).forEach { (permission, consequence) ->
            assertTrue(
                "$which does not declare $permission - $consequence",
                manifest.contains(permission),
            )
        }
    }

    @Test
    fun `an off-device recipient is a host the app actually contacts`() {
        // A row claiming a recipient nothing contacts would overstate the
        // disclosure; a feature contacting a host no row names would understate
        // it, which is the worse direction. Both are caught here.
        val sourceHosts = File("src/main/java")
            .walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .flatMap { Regex("""https://([a-zA-Z0-9.-]+)""").findAll(it.readText()) }
            .map { it.groupValues[1] }
            .toSet()

        val claimed = PermissionRegistry.offDevice
            .mapNotNull { it.destination as? PermissionCapability.Destination.OffDevice }
            .flatMap { it.hosts }
            .toSet()

        val notContacted = (claimed - sourceHosts).sorted()
        assertTrue("the registry names hosts no source file contacts: $notContacted", notContacted.isEmpty())

        // example.com appears only as a placeholder and as an intent probe for
        // finding the default browser; neither transmits anything.
        val placeholders = setOf("example.com", "www.example.com", "open-meteo.com", "nominatim.org")
        val undisclosed = (sourceHosts - claimed - placeholders).sorted()
        assertTrue(
            "these hosts are contacted but no capability row discloses them: $undisclosed",
            undisclosed.isEmpty(),
        )
    }

    @Test
    fun `every row answers every question`() {
        // A blank field here becomes a blank answer on the Data Safety form.
        PermissionRegistry.capabilities.forEach { capability ->
            // A name is allowed to be short - "Files" and "Photos" are the
            // right answers for `feature`, and an earlier length floor here
            // flagged them as empty. The prose fields are the ones where a
            // three-word answer means nobody wrote one.
            listOf("feature" to capability.feature, "settingsPath" to capability.settingsPath)
                .forEach { (field, value) ->
                    assertTrue("${capability.permission} has a blank $field", value.isNotBlank())
                }
            listOf(
                "userValue" to capability.userValue,
                "scope" to capability.scope,
                "onDenial" to capability.onDenial,
            ).forEach { (field, value) ->
                assertTrue(
                    "${capability.permission} has no real $field - this becomes a blank " +
                        "answer on the Data Safety form",
                    value.isNotBlank() && value.length > 24,
                )
            }
        }
    }

    @Test
    fun `no permission is registered twice`() {
        val duplicates = PermissionRegistry.capabilities
            .groupBy { it.permission }
            .filterValues { it.size > 1 }
            .keys
            .sorted()
        assertTrue("duplicate rows would give a reviewer two answers: $duplicates", duplicates.isEmpty())
    }

    @Test
    fun `the restricted permissions are the ones flagged for a Play declaration`() {
        // These four are what Play judges against the app's core purpose.
        // Silently dropping one from the declaration set is how a submission
        // fails review, so the set is pinned rather than derived.
        val expected = setOf(
            "android.permission.QUERY_ALL_PACKAGES",
            "android.permission.MANAGE_EXTERNAL_STORAGE",
            "android.permission.READ_MEDIA_IMAGES",
            "android.permission.READ_MEDIA_VIDEO",
        )
        val flagged = PermissionRegistry.capabilities
            .filter { it.playDeclaration == PermissionCapability.PlayDeclaration.DECLARATION_FORM }
            .map { it.permission }
            .toSet()
        assertTrue(
            "expected exactly the restricted permissions to need a declaration form, got $flagged",
            flagged == expected,
        )
    }

    @Test
    fun `the data inventory documents every capability`() {
        // The inventory is the artefact a Play reviewer and the privacy policy
        // both read. A capability added in code and forgotten in the document
        // is precisely the drift this whole registry exists to stop.
        val inventory = File("../DATA_INVENTORY.md")
        assertTrue("DATA_INVENTORY.md is missing at ${inventory.absolutePath}", inventory.exists())
        val text = inventory.readText()

        val undocumented = PermissionRegistry.capabilities
            .map { it.permission.substringAfterLast('.') }
            .filterNot { text.contains(it) }
            .sorted()
        assertTrue("DATA_INVENTORY.md does not mention: $undocumented", undocumented.isEmpty())
    }
}
